[package]
name = "final_redis"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
redis = "0.20.0"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = "0.2"
